### PR TITLE
Removed idea config files

### PR DESCRIPTION
**Pull request by rosenpin**

### CODE REVIEW

**Comment by DavidEdwards** [comment]
I don't mind getting rid of the idea files, but why?

They are usually kept in git.

**Comment by rosenpin** [comment]
Those are usually removed, basically, if I open a project with your idea files, my ide might try to use the project (your) ide configuration, in any case, this is bad practice

**Comment by DavidEdwards** [comment]
From intellij itself:

> Almost all of the files contain information core to the project itself, such as names and locations of its component modules, compiler settings, etc. Thus, these files may (and should) be kept under version control.

Ill check this later.

**Comment by rosenpin** [comment]
Maybe that's the case for non Android projects, but I never ran into an Android project that I couldn't build without the .idea files.

**Comment by DavidEdwards** [comment]
I'll pass this through, as far as I am able to tell, it can't hurt.

**Pull request merged**
