### PR TITLE
Feature/custom theme

### PR DESCRIPTION
**Pull request by rosenpin**
You can now set custom themes using the
useTheme method.

Issues:
If you use a very light theme for the primary color (uncommon) the toolbar text will be hard to read.

### CODE REVIEW

**Comment by DavidEdwards** [comment]
My plan was for the interface to echo the new "Material 2" standards that Google is pushing.

The general idea of this is that the whole UI is white, shadows are separating content and important eye catching features are coloured. In this case, the new green toolbar / status bar are conflicting with this.

This should be the default state. I am happy for changes to the default state being made through the use of the useTheme method.

**Comment by rosenpin** [comment]
Didn't have time yet to look into Material Design 2.
Everything should be white now?
That sounds pretty bad.
Anyway, changing it should be easy, just change the default theme back.
I don't think I'll have time to do this this week. I won't be home again until Friday.

**Comment by DavidEdwards** [comment]
Here is an example.

image

As you can see there is very little use of colour.

**Comment by rosenpin** [comment]
Got it, I'll look into it next Friday if I get the chance.
Thanks

**Comment by DavidEdwards** [comment]
Closing this due to activity.

**Pull request closed without merging**
